version: '3'

services:

  db:
    image: postgres
    
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django:
    build: "./aiki_django"

    ports: 
      - "8000:8000"

    volumes:
      - "./aiki_django/:/aiki_django/"

    depends_on:
      - db

  # react:
  #   build: "./aiki_react"

  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"

  #   ports:
  #     - "3000:3000"

  #   volumes:
  #     - "./aiki_react/:/app/"

  #   depends_on:
  #     - django