version: '3'

services:

  db:
    image: postgres
    
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .

    ports: 
      - "8000:8000"

    volumes:
      - "./aiki/:/project/"

    depends_on:
      - db
