# Generated by Django 4.0.1 on 2022-03-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aikiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
